In [1]:
from ast import literal_eval
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from tqdm import tqdm
import openpyxl

import warnings
warnings.filterwarnings('ignore')

In [23]:
import glob

csv_files = glob.glob("data/*.csv")
df = [pd.read_csv(file) for file in csv_files]

In [47]:
df[0].head()

,driver_id,rating,vehicle_type,signup_date,last_active,city,acceptance_rate
0,D00000,3.1,SUV,2025-01-20,2025-01-06 18:23:09.312275,Cairo,0.679555
1,D00001,5.0,Sedan,2023-03-27,2025-04-27 01:44:02.472554,Nairobi,0.548786
2,D00002,4.5,Motorcycle,2024-05-02,2025-03-07 19:24:46.367672,Nairobi,0.593724
3,D00003,5.0,Motorcycle,2023-04-16,2025-03-26 19:16:24.253793,Nairobi,0.990000
4,D00004,4.4,Motorcycle,2023-05-28,2025-04-08 18:54:44.649615,Lagos,0.519773

In [65]:
df[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   driver_id        5000 non-null   object
 1   rating           5000 non-null   float64
 2   vehicle_type     5000 non-null   object
 3   signup_date      5000 non-null   object
 4   last_active      5000 non-null   object
 5   city             5000 non-null   object
 6   acceptance_rate  5000 non-null   float64
dtypes: float64(2), object(5)
memory usage: 273.6+ KB

In [49]:
df[1].head()

,promo_id,promo_name,promo_type,promo_value,start_date,end_date,target_segment,city_scope,ab_test_groups,test_allocation,success_metric
0,P000,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-25,All,Nairobi,['All'],[1.0],Usage Frequency
1,P001,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-22,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
2,P002,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-16,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
3,P003,Loyalty Bonus,points,100.0,2025-04-26,2025-05-04,Gold+,Nairobi,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
4,P004,Loyalty Bonus,points,100.0,2025-04-26,2025-05-15,Gold+,Nairobi,['All'],[1.0],Usage Frequency

In [69]:
df[1].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   promo_id         20 non-null     object
 1   promo_name       20 non-null     object
 2   promo_type       20 non-null     object
 3   promo_value      20 non-null     float64
 4   start_date       20 non-null     object
 5   end_date         20 non-null     object
 6   target_segment   20 non-null     object
 7   city_scope       20 non-null     object
 8   ab_test_groups   20 non-null     object
 9   test_allocation  20 non-null     object
 10  success_metric   20 non-null     object
dtypes: float64(1), object(10)
memory usage: 1.8+ KB

In [51]:
df[2].head()

,user_id,signup_date,loyalty_status,age,city,avg_rating_given,churn_prob,referred_by
0,R00000,2025-01-24,Bronze,34.729629,Nairobi,5.0,0.142431,R00001
1,R00001,2024-09-09,Bronze,34.571020,Nairobi,4.7,0.674161,NaN
2,R00002,2024-09-07,Bronze,47.133960,Lagos,4.2,0.510379,NaN
3,R00003,2025-03-17,Bronze,41.658628,Nairobi,4.9,0.244779,NaN
4,R00004,2024-08-20,Silver,40.681709,Lagos,3.9,0.269960,R00002

In [71]:
df[2].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           10000 non-null  object
 1   signup_date       10000 non-null  object
 2   loyalty_status    10000 non-null  object
 3   age               10000 non-null  float64
 4   city              10000 non-null  object
 5   avg_rating_given  10000 non-null  float64
 6   churn_prob        10000 non-null  float64
 7   referred_by       3053 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

In [53]:
df[3].head()

,session_id,rider_id,session_time,time_on_app,pages_visited,converted,city,loyalty_status
0,S000000,R08605,2025-04-27 18:57:06+02:05,79,4,1,Cairo,Bronze
1,S000001,R08823,2025-04-27 07:32:22+02:27,101,3,0,Nairobi,Silver
2,S000002,R05342,2025-04-27 23:17:25+02:05,12,1,0,Cairo,Bronze
3,S000003,R05057,2025-04-27 14:40:25+00:14,19,1,0,Lagos,Silver
4,S000004,R09614,2025-04-27 08:31:22+00:14,4,1,0,Lagos,Bronze

In [73]:
df[3].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   session_id      50000 non-null  object
 1   rider_id        50000 non-null  object
 2   session_time    50000 non-null  object
 3   time_on_app     50000 non-null  int64
 4   pages_visited   50000 non-null  int64
 5   converted       50000 non-null  int64
 6   city            50000 non-null  object
 7   loyalty_status  50000 non-null  object
dtypes: int64(3), object(5)
memory usage: 3.1+ MB

In [57]:
df[4].head()

,trip_id,user_id,driver_id,fare,surge_multiplier,tip,payment_type,pickup_time,dropoff_time,pickup_lat,pickup_lng,dropoff_lat,dropoff_lng,weather,city,loyalty_status
0,T000000,R05207,D00315,12.11,1.0,0.00,Card,2024-11-27 18:41:50+02:27,2024-11-27 19:33:50+02:27,-1.108123,36.912209,-1.068155,36.875377,Foggy,Nairobi,Bronze
1,T000001,R09453,D03717,8.73,1.0,0.02,Card,2024-10-28 23:13:48+00:14,2024-10-28 23:26:48+00:14,6.675266,3.515740,6.641734,3.525620,Sunny,Lagos,Gold
2,T000002,R00567,D02035,19.68,1.0,0.00,Card,2025-02-17 05:36:41+02:27,2025-02-17 05:52:41+02:27,-1.248589,37.010668,-1.273182,37.018586,Cloudy,Nairobi,Bronze
3,T000003,R09573,D02657,16.43,1.0,0.01,Mobile Money,2024-06-18 19:27:14+02:05,2024-06-18 19:32:14+02:05,29.819554,31.188780,29.837689,31.232978,Cloudy,Cairo,Bronze
4,T000004,R03446,D01026,8.70,1.0,1.06,Card,2024-10-05 09:58:16+02:27,2024-10-05 10:28:16+02:27,-1.676479,36.729219,-1.638395,36.694063,Sunny,Nairobi,Gold

In [75]:
df[4].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   trip_id           200000 non-null  object
 1   user_id           200000 non-null  object
 2   driver_id         200000 non-null  object
 3   fare              200000 non-null  float64
 4   surge_multiplier  200000 non-null  float64
 5   tip               200000 non-null  float64
 6   payment_type      200000 non-null  object
 7   pickup_time       200000 non-null  object
 8   dropoff_time      200000 non-null  object
 9   pickup_lat        200000 non-null  float64
 10  pickup_lng        200000 non-null  float64
 11  dropoff_lat       200000 non-null  float64
 12  dropoff_lng       200000 non-null  float64
 13  weather           200000 non-null  object
 14  city              200000 non-null  object
 15  loyalty_status    200000 non-null  object
dtypes: float64(7), object(9)
memory usage: 24.4+ MB

In [59]:
df[5].head()

,trip_id,user_id,driver_id,fare,surge_multiplier,tip,payment_type,pickup_time,dropoff_time,pickup_lat,pickup_lng,dropoff_lat,dropoff_lng,weather,city,loyalty_status
0,T066468,R05030,D03970,23.39,1.3,1.42,Card,2024-12-08 23:34:36+02:27,2024-12-09 00:29:36+02:27,-1.351910,36.676170,-1.401868,36.699019,Rainy,Nairobi,Silver
1,T041539,R03969,D02461,27.25,1.1,0.00,Mobile Money,2024-10-07 16:17:04+02:27,2024-10-07 16:26:04+02:27,-1.210869,36.921479,-1.199794,36.923274,Rainy,Nairobi,Silver
2,T066263,R01074,D00259,6.51,1.0,0.00,Card,2025-01-28 23:05:49+02:27,2025-01-28 23:24:49+02:27,-1.213306,36.912171,-1.211032,36.957163,Rainy,Nairobi,Platinum
3,T176914,R08081,D00184,11.19,1.0,3.73,Card,2024-05-21 18:12:10+00:14,2024-05-21 19:11:10+00:14,6.383939,3.220365,6.369803,3.240972,Cloudy,Lagos,Silver
4,T040747,R05309,D03452,18.25,1.0,0.00,Card,2025-04-15 10:29:08+02:05,2025-04-15 11:26:08+02:05,30.052523,31.337210,30.094971,31.316696,Sunny,Cairo,Bronze

In [63]:
df[5].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   trip_id           50000 non-null  object
 1   user_id           50000 non-null  object
 2   driver_id         50000 non-null  object
 3   fare              50000 non-null  float64
 4   surge_multiplier  50000 non-null  float64
 5   tip               50000 non-null  float64
 6   payment_type      50000 non-null  object
 7   pickup_time       50000 non-null  object
 8   dropoff_time      50000 non-null  object
 9   pickup_lat        50000 non-null  float64
 10  pickup_lng        50000 non-null  float64
 11  dropoff_lat       50000 non-null  float64
 12  dropoff_lng       50000 non-null  float64
 13  weather           50000 non-null  object
 14  city              50000 non-null  object
 15  loyalty_status    50000 non-null  object
dtypes: float64(7), object(9)
memory usage: 6.1+ MB